import type { Category, Product, Employee, POSSettings } from '../types';

export const INITIAL_SETTINGS: POSSettings = {
  cafeId: 'cafe-dushanbe-01',
  cafeName: 'Coffee House',
  currency: 'сомони',
  adminPin: '',
  taxRatePercent: 0,
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-coffee',
    name: 'Кофе',
    accentBg: 'bg-[#FDF3E3] dark:bg-[#2A2317] text-[#854D0E] dark:text-[#FDE68A] border-[#FDE68A]/60',
    accentColor: '#F59E0B',
    icon: '☕',
  },
  {
    id: 'cat-food',
    name: 'Еда',
    accentBg: 'bg-[#EBF5FF] dark:bg-[#162338] text-[#1E40AF] dark:text-[#93C5FD] border-[#93C5FD]/60',
    accentColor: '#3B82F6',
    icon: '🍔',
  },
  {
    id: 'cat-desserts',
    name: 'Десерты',
    accentBg: 'bg-[#FDF2F8] dark:bg-[#311728] text-[#9D174D] dark:text-[#F472B6] border-[#F472B6]/60',
    accentColor: '#EC4899',
    icon: '🍰',
  },
  {
    id: 'cat-drinks',
    name: 'Напитки',
    accentBg: 'bg-[#ECFDF5] dark:bg-[#122B22] text-[#065F46] dark:text-[#6EE7B7] border-[#6EE7B7]/60',
    accentColor: '#10B981',
    icon: '🥤',
  },
  {
    id: 'cat-tea',
    name: 'Чай',
    accentBg: 'bg-[#F5F3FF] dark:bg-[#231A3A] text-[#5B21B6] dark:text-[#C4B5FD] border-[#C4B5FD]/60',
    accentColor: '#8B5CF6',
    icon: '🫖',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Кофе
  {
    id: 'prod-americano',
    name: 'Американо',
    categoryId: 'cat-coffee',
    price: 15,
    costPrice: 4.5,
    active: true,
    icon: '☕',
    description: 'Классический эспрессо с горячей водой 250 мл',
  },
  {
    id: 'prod-cappuccino',
    name: 'Капучино',
    categoryId: 'cat-coffee',
    price: 20,
    costPrice: 6.0,
    active: true,
    icon: '☕',
    description: 'Эспрессо с шелковистой молочной пенкой 300 мл',
  },
  {
    id: 'prod-latte',
    name: 'Латте',
    categoryId: 'cat-coffee',
    price: 22,
    costPrice: 7.0,
    active: true,
    icon: '🥛',
    description: 'Нежный кофейно-молочный напиток 350 мл',
  },
  {
    id: 'prod-espresso',
    name: 'Эспрессо',
    categoryId: 'cat-coffee',
    price: 12,
    costPrice: 3.5,
    active: true,
    icon: '⚡',
    description: 'Плотный шот свежеобжаренного кофе 35 мл',
  },
  {
    id: 'prod-flatwhite',
    name: 'Флэт Уайт',
    categoryId: 'cat-coffee',
    price: 22,
    costPrice: 7.5,
    active: true,
    icon: '☕',
    description: 'Двойной эспрессо с тонким слоем молока',
  },
  // Еда
  {
    id: 'prod-burger',
    name: 'Бургер',
    categoryId: 'cat-food',
    price: 35,
    costPrice: 16.0,
    active: true,
    icon: '🍔',
    description: 'Сочная говяжья котлета, сыр чеддер, свежие томаты',
  },
  {
    id: 'prod-pizza',
    name: 'Пицца',
    categoryId: 'cat-food',
    price: 45,
    costPrice: 18.0,
    active: true,
    icon: '🍕',
    description: 'Хрустящая пицца с моцареллой и соусом песто',
  },
  {
    id: 'prod-fries',
    name: 'Фри',
    categoryId: 'cat-food',
    price: 15,
    costPrice: 5.0,
    active: true,
    icon: '🍟',
    description: 'Золотистый картофель фри с морской солью',
  },
  {
    id: 'prod-sandwich',
    name: 'Клаб-сэндвич',
    categoryId: 'cat-food',
    price: 28,
    costPrice: 11.0,
    active: true,
    icon: '🥪',
    description: 'С куриным филе, беконом и свежим салатом',
  },
  // Десерты
  {
    id: 'prod-cheesecake',
    name: 'Чизкейк Нью-Йорк',
    categoryId: 'cat-desserts',
    price: 24,
    costPrice: 9.0,
    active: true,
    icon: '🍰',
    description: 'Нежный сливочный чизкейк с ванилью',
  },
  {
    id: 'prod-croissant',
    name: 'Круассан',
    categoryId: 'cat-desserts',
    price: 14,
    costPrice: 4.5,
    active: true,
    icon: '🥐',
    description: 'Хрустящий французский круассан со сливочным маслом',
  },
  // Напитки
  {
    id: 'prod-lemonade',
    name: 'Лимонад Цитрус',
    categoryId: 'cat-drinks',
    price: 16,
    costPrice: 5.0,
    active: true,
    icon: '🍋',
    description: 'Освежающий лимонад с мятой и апельсином',
  },
  {
    id: 'prod-tea',
    name: 'Чай Чайник',
    categoryId: 'cat-tea',
    price: 10,
    costPrice: 2.0,
    active: true,
    icon: '🫖',
    description: 'Зеленый или черный чай в чайнике 600 мл',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-ali',
    name: 'Али',
    pin: '1111',
    role: 'barista',
    active: true,
  },
  {
    id: 'emp-said',
    name: 'Саид',
    pin: '2222',
    role: 'cashier',
    active: true,
  },
  {
    id: 'emp-muhammad',
    name: 'Мухаммад',
    pin: '3333',
    role: 'barista',
    active: true,
  },
];
